# Site settings
author: Kerri OGorman
title: The Coding Newby
header-img: img/home-bg.png
email: kerri.l.ogorman@gmail.com
copyright_name: Kerri OGorman
description: > # this means to ignore newlines until "baseurl:"
  Codes and thoughts from an early programmer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  KerriLynne

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
